Add specificaion
hse-wasd-team/werec pull request #31
Opened 2022-10-12 17:22 UTC by ramilyayus

#18

2022-10-13 15:09 UTC, aalexsm requested changes

2022-10-13 15:09 UTC, aalexsm commented on specification.yml
> +  url: https://github.com/ramilyayus/WeRec-specs
Change link to repo

2022-10-13 15:09 UTC, aalexsm commented on specification.yml
> +  /videos/{feedId}/{keyword}/:
Shouldn't it be like feedId/config/keyword?

2022-10-13 15:15 UTC, zhurbey commented
может добавим префикс к ручкам, что-то вроде /api/v1/<>

2022-10-15 09:48 UTC, ramilyayus commented on specification.yml
> +  /videos/{feedId}/{keyword}/:
not necessary, this endpoint produces videos not configs, i think it is better to separate them
@zhurbey what do you think?

2022-10-16 14:58 UTC, aalexsm commented on specification.yml
> +  /videos/{feedId}/{keyword}/:
@zhurbey please help us to solve and we'll merge

2022-10-16 18:55 UTC, zhurbey commented
пара коротких замечаний в воздух:

1. определенно возвращать комменты в ручке get /feed идея довольно странная, так точно лучше не делать, а выделить этот кусок в отдельную ручку, в ней прикрутить логику пагинации. Конфиги наверное стоит все-таки подтягивать, так как чаще всего могут требоваться вместе. Вообще это касается всех мест где возвращаются фиды
2. оборачивать данные в ответах стоит в {“data”: {и тут ответ}}. Так стоит делать во всех ручках, в том числе в запросах на сервак
3. rating -> review
4. думаю что в put запросах на фиды не стоит прикладывать конфигурации, в них редачить только метаинфу самих фидов,  на конфиги сделать отдельную ручку. Хотя честно не уверен, возможно в каких-то сценариях так будет и правда проще, но такая логика bulk update’а все равно скорее всего должна быть в другом месте 

смотрел не сильно детально и думаю что когда будем писать код что-то все равно будет сильно меняться, по этим коментам тоже ничего править не нужно. Го вливать)

@ramilyayus

2022-10-16 18:56 UTC, zhurbey approved these changes

2022-10-16 18:56 UTC, zhurbey commented on specification.yml
> +  /videos/{feedId}/{keyword}/:
> not necessary, this endpoint produces videos not configs, i think it is better to separate them @zhurbey what do you think?

yep, you're right, makes no sense to access configs through videos

2022-10-16 19:02 UTC, aalexsm approved these changes

2022-10-16 19:04 UTC, merged